template:
  path: application.yaml.j2
  type: file

parameters:
  AppName: !stack_attr sceptre_user_data.app_name
  Env: !stack_attr sceptre_user_data.env

  ECRRepositoryUri: !stack_output dev/data.yaml::ECRRepositoryURI

  DynamoTableArn: !stack_output dev/data.yaml::DynamoTableArn
  DynamoTableName: !stack_output dev/data.yaml::DynamoTableName

  S3BucketId: !stack_output dev/data.yaml::S3BucketId
  S3BucketArn: !stack_output dev/data.yaml::S3BucketArn

  SqsQueueId: !stack_output dev/data.yaml::SqsQueueId
  SqsQueueArn: !stack_output dev/data.yaml::SqsQueueArn
  SnsTopicDownloadName: !stack_output dev/data.yaml::SnsTopicDownloadName
  SnsTopicNotificationName: !stack_output dev/data.yaml::SnsTopicNotificationName
  SnsTopicPublicationName: !stack_output dev/data.yaml::SnsTopicPublicationName

  LogGroupArn: !stack_output dev/data.yaml::LogGroupArn
