template:
  path: 'cognito.yaml'
  type: 'file'

parameters:
  DomainName: !stack_attr sceptre_user_data.domain
  NamePrefix: !stack_attr sceptre_user_data.resource_name_prefix
  CertificateArn: !stack_output dev/data.yaml::CertificateArn
  Env: !stack_attr sceptre_user_data.env

  DmptoolCallbackUri: 'https://dmptool-dev.cdlib.org/callback'
