template:
  path: data.yaml
  type: file

parameters:
  AppName: !stack_attr sceptre_user_data.app_name
  DomainName: !stack_attr sceptre_user_data.domain
  Environment: !stack_attr sceptre_user_data.env

  HostedZoneId: !stack_output_external sceptre-uc3-ops-common-dev-route53::HostedZoneID

  ECRLifecyclePolicyTagPrefix: 'latest'
